/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_prvc.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_pz.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_rise.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_index.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_fall.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_prvcs.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_catch_cnt_daily.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_brief_market.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_brief_prvc.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_brief_pz.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_variation_daily.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_prvc_variation_daily.json
/opt/module/datax/bin/datax.py /export/agrimarket/datax/ads_price_prvc_peak_daily.json